name: "Detect changes"
description: "Decide what steps need running based on changes"
inputs:
  changes:
    description: "JSON array of changed files"
    required: true
runs:
  using: "composite"
  steps:
    - id: actionlint
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard actionlint.yml
    - id: go
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard go.yml
    - id: golangci-lint
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard golangci-lint.yml
    - id: brew
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard brew.yml
    - id: github
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard github.yml
    - id: nix
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard nix.yml
    - id: mkdocs
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard mkdocs.yml
    - id: prettier
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard prettier.yml
    - id: shellcheck
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard shellcheck.yml
outputs:
  actionlint:
    description: "Whether actionlint has changed"
    value: ${{ steps.actionlint.outputs.changed }}
  go:
    description: "Whether Go has changed"
    value: ${{ steps.go.outputs.changed }}
  golangci-lint:
    description: "Whether golangci-lint has changed"
    value: ${{ steps.golangci-lint.outputs.changed }}
  brew:
    description: "Whether Brew has changed"
    value: ${{ steps.brew.outputs.changed }}
  github:
    description: "Whether GitHub has changed"
    value: ${{ steps.github.outputs.changed }}
  nix:
    description: "Whether Nix has changed"
    value: ${{ steps.nix.outputs.changed }}
  release:
    description: "Whether any release has changed"
    value: ${{ steps.brew.outputs.changed || steps.github.outputs.changed || steps.nix.outputs.changed }}
  mkdocs:
    description: "Whether MkDocs has changed"
    value: ${{ steps.mkdocs.outputs.changed }}
  prettier:
    description: "Whether Prettier has changed"
    value: ${{ steps.prettier.outputs.changed }}
  shellcheck:
    description: "Whether ShellCheck has changed"
    value: ${{ steps.shellcheck.outputs.changed }}
