name: "Release GitHub"
description: "Create a GitHub Release"
inputs:
  version:
    description: "Version to release"
    required: true
  anttiharju-bot-id:
    description: "GitHub App ID for anttiharju[bot]"
    required: true
  anttiharju-bot-private-key:
    description: "GitHub App private key for anttiharju[bot]"
    required: true
runs:
  using: "composite"
  steps:
    - name: Tag current commit
      shell: sh
      env:
        tag: "v${{ inputs.version }}"
      run: |
        git tag "$tag"
    - name: Create darwin-arm64 archive
      shell: sh
      env:
        tag: "v${{ inputs.version }}"
      run: |
        .release/archive.sh "$tag" darwin arm64
    - name: Create linux-arm64 archive
      shell: sh
      env:
        tag: "v${{ inputs.version }}"
      run: |
        .release/archive.sh "$tag" linux arm64
    - name: Create linux-amd64 archive
      shell: sh
      env:
        tag: "v${{ inputs.version }}"
      run: |
        .release/archive.sh "$tag" linux amd64
    - name: Release
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
        title: ${{ inputs.version }}
        tag: "v${{ inputs.version }}"
      run: |
        git reset --hard && git clean -df
        git push origin "$tag"
        gh release create "$tag" --title="$title" --generate-notes --draft
        find . -maxdepth 1 -name '${{ github.event.repository.name }}-*.tar.gz' -exec gh release upload "$tag" {} \;
        gh release edit "$tag" --draft=false
