name: Plan
on:
  pull_request:
    # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
    # defaults: opened, synchronize, reopened
    types: [opened, synchronize, reopened, labeled, unlabeled]
  workflow_call:
    outputs:
      release:
        description: "Whether to trigger release workflows"
        value: ${{ jobs.validate.outputs.release_type != '' || (jobs.validate.outputs.binary_changed == 'true' || jobs.validate.outputs.dist_changed == 'true') }}
      release_type:
        description: "The type of release to perform; major, minor, patch, or empty"
        value: ${{ jobs.validate.outputs.release_type }}
      documentation:
        description: "Whether to update the documentation website"
        value: ${{ jobs.validate.outputs.documentation_changed == 'true' }}

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-24.04
    steps:
      - name: Find changes
        id: changes
        uses: anttiharju/actions/find-changes@9806aee2daa32397215f0d26dedea4dbe1904fff

      - name: Detect changes
        id: changed
        uses: ./.github/actions/detect-changes
        with:
          changes: ${{ steps.changes.outputs.array }}

      - if: always()
        id: semver
        name: Require semantic version label
        uses: anttiharju/actions/require-semver-label@9806aee2daa32397215f0d26dedea4dbe1904fff
        with:
          enforce: ${{ (steps.changed.outputs.binary == 'true' || steps.changed.outputs.dist_brew == 'true' || steps.changed.outputs.dist_github == 'true') && github.event_name != 'push' }}

      - if: always()
        name: action-validator
        uses: anttiharju/actions/action-validator@9806aee2daa32397215f0d26dedea4dbe1904fff

      - if: always() && (steps.changed.outputs.github_actions_workflows == 'true' || github.event_name != 'pull_request')
        name: actionlint
        uses: anttiharju/actions/actionlint@9806aee2daa32397215f0d26dedea4dbe1904fff

      - if: always()
        name: relcheck
        uses: anttiharju/actions/relcheck@9806aee2daa32397215f0d26dedea4dbe1904fff

      - if: always()
        name: EditorConfig-Checker
        uses: anttiharju/actions/editorconfig-checker@9806aee2daa32397215f0d26dedea4dbe1904fff

      - if: always() && (steps.changed.outputs.binary == 'true' || github.event_name != 'pull_request')
        name: go build
        uses: anttiharju/actions/go-build@9806aee2daa32397215f0d26dedea4dbe1904fff

      - if: always() && (steps.changed.outputs.binary == 'true' || github.event_name != 'pull_request')
        name: go test
        shell: sh
        run: |
          go test ./...

      - if: always() && (steps.changed.outputs.go_code == 'true' || github.event_name != 'pull_request')
        name: golangci-lint
        uses: anttiharju/actions/golangci-lint@9806aee2daa32397215f0d26dedea4dbe1904fff

      - if: always()
        name: Keep .yml
        uses: anttiharju/actions/keep-yml@9806aee2daa32397215f0d26dedea4dbe1904fff

      - if: always() && (steps.changed.outputs.documentation == 'true' || github.event_name != 'pull_request')
        name: MkDocs
        uses: anttiharju/actions/mkdocs-build-strict@9806aee2daa32397215f0d26dedea4dbe1904fff

      - if: always() && (steps.changed.outputs.md_and_yml == 'true' || github.event_name != 'pull_request')
        name: Prettier
        uses: anttiharju/actions/prettier@9806aee2daa32397215f0d26dedea4dbe1904fff
        with:
          patterns: "{*.yml,*.md}"

      - if: always() && (steps.changed.outputs.dist_brew == 'true' || github.event_name != 'pull_request')
        name: Rubocop formula
        uses: ./.github/actions/rubocop-formula

      - if: always() && (steps.changed.outputs.scripts == 'true' || github.event_name != 'pull_request')
        name: ShellCheck
        uses: anttiharju/actions/shellcheck@9806aee2daa32397215f0d26dedea4dbe1904fff
    outputs:
      binary_changed: ${{ steps.changed.outputs.binary }}
      dist_changed: ${{ steps.changed.outputs.dist_brew || steps.changed.outputs.dist_github }}
      release_type: ${{ steps.semver.outputs.bump }}
      documentation_changed: ${{ steps.changed.outputs.documentation }}
